export const DEFAULT_COLUMNS = [
  {
    label: 'Name',
    field: 'name',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Email',
    field: 'email',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Country',
    field: 'country',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Region',
    field: 'region',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Zip',
    field: 'zip',
    sorting: 'ASC',
    type: 'number',
    defaultValue: '',
    value: '',
  },
  {
    label: 'IsUser',
    field: 'isUser',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
];
