export const DEFAULT_COLUMNS = [
  {
    label: 'Order No',
    field: 'order',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Quantity',
    field: 'quantity',
    sorting: 'ASC',
    type: 'number',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Name',
    field: 'name',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Age',
    field: 'age',
    sorting: 'ASC',
    type: 'number',
    defaultValue: '',
    value: '',
  },
  {
    label: 'Gender',
    field: 'gender',
    sorting: 'ASC',
    type: 'text',
    defaultValue: '',
    value: '',
  },
];
